##############################################
#               MY PLUGINS                   #
##############################################

plugins:
  sumit:
    executor: central_deployment_agent
    source: https://github.com/sumitdawar/clodifyTest/archive/master.zip